### PR TITLE
EP-4803: Fix domain for password reset email

### PR DESCRIPTION
**Pull request by radome**

### CODE REVIEW

**Comment by radome** [comment]
> The uri need to be updated after this fixture is loaded, is this intended ?

Yes. I think it's safer to have an exception thrown than (potentially) modify production data by default. Like when deploying locally for development and being already signed in on the production admin page.

Ideally the admin page link should automatically point to the admin page of the server that is handling the request.

**Comment by marcoooo** [comment]
> > The uri need to be updated after this fixture is loaded, is this intended ?
> 
> Yes. I think it's safer to have an exception thrown than (potentially) modify production data by default. Like when deploying locally for development and being already signed in on the production admin page.
> 
> Ideally the admin page link should automatically point to the admin page of the server that is handling the request.

I got your point and this is fine then :-) May it worth an update on other to do the same thing (not pointing directly to live services but only the same local one each time - you are free to select the port

**Comment by radome** [comment]
> > > The uri need to be updated after this fixture is loaded, is this intended ?
> > 
> > 
> > Yes. I think it's safer to have an exception thrown than (potentially) modify production data by default. Like when deploying locally for development and being already signed in on the production admin page.
> > Ideally the admin page link should automatically point to the admin page of the server that is handling the request.
> 
> I got your point and this is fine then :-) May it worth an update on other to do the same thing (not pointing directly to live services but only the same local one each time - you are free to select the port

Done 👍

**Comment by radome** [comment]
> May I add another remark: what do you think to use the same port for all "services" instead ? This could help for local development to have only one setup for all basically "same services" deployed but for different division. Not sure within "local" setup it worths having 3 separated disctint divisions "copy / Handover / Metadata /..." services available.

I would leave that as it is, partially for "documentation" but also because even locally apps should be separated in order to mimic the production environment and reduce the chances to overlook things.

**Comment by marcoooo** [comment]
> > May I add another remark: what do you think to use the same port for all "services" instead ? This could help for local development to have only one setup for all basically "same services" deployed but for different division. Not sure within "local" setup it worths having 3 separated disctint divisions "copy / Handover / Metadata /..." services available.
> 
> I would leave that as it is, partially for "documentation" but also because even locally apps should be separated in order to mimic the production environment and reduce the chances to overlook things.

I would argue they all work the same way, and having to set up 3 duplicated services stack locally could be painful

**Pull request merged**
